{
 "title": "Weather Demo Dashboard",
 "tags": [ "Weather" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Forecasts Request Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "forecast_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Temperature in Last Forecast Set",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "average_forecast_temperature_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extreme Forecast Summary Counter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "extreme_forecast_counter_total",
     "legendFormat": "{{label_name}}{{forecast_summary}}"
    }
   ]
  },
  {
   "title": "Total seconds spent processing forecast requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forecast_processing_time_sum / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(forecast_processing_time_sum[30m]) / rate(forecast_processing_time_count[30m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}