global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Have prometheus scrape itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.252.66:9090']

  # Scrape node exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.252.66:9100']
  
  # Scrape cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.252.66:8085']
 
  # Scrape otel-collector's internal metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['192.168.252.66:8888']

  # Scrape Loki's internal metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['192.168.252.66:3100']

  # Scrape app metrics from otel-collector
  - job_name: 'apps'
    static_configs:
      - targets: ['192.168.252.66:8889']

  # Scrape fildsd
  - job_name: 'filesd'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
        refresh_interval: 5s

  # Scrape Docker Swarm Nodes
  - job_name: 'docker_nodes'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      - source_labels: [__meta_dockerswarm_node_id]
        target_label: node_id
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

