services:
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    volumes:
      - ./config/prometheus:/etc/prometheus
    extra_hosts:
      host.docker.internal: host-gateway
      
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: [ "--config=/etc/collector.yaml" ]
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
      - 8889:8889
      - 13133:13133
      - 55679:55679
    volumes:
      - ./config/otel-collector-config.yaml:/etc/collector.yaml

  tempo:
    image: grafana/tempo:2.6.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml

  loki:
    image: grafana/loki:3.2.0
    command: ["--config.file=/etc/loki-config.yaml"]
    ports:
      - 3100:3100
    volumes:
      - ./config/loki-config.yaml:/etc/loki-config.yaml

  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  weatherapp:
    image: 192.168.252.66:5001/distributed-system-mvp/weather-app:0.0.2-otel-collector
    ports:
      - 8080:8080
