receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

  otlp/traces:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]

    traces:
      receivers: [otlp]
      exporters: [debug, otlp/traces]

  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888

