apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    uid: prometheus

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '\"traceid\":\"(.*?)\"'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: View Trace

